package router

import (
	"github.com/gin-gonic/gin"
	"github.com/latiiLA/CoopInsight/backend/internal/delivery/http/handler"
	"github.com/latiiLA/CoopInsight/backend/internal/delivery/http/middleware"
)

func registerReportRoutes(
	protected *gin.RouterGroup,
	successTransactionHandler handler.SuccessTransactionHandler,
	ebirrCardlessHandler handler.EbirrCardlessWithdrawalHandler,
	terminalTransactionHandler handler.TerminalTransactionHandler,
) {
	reports := protected.Group("/reports")

	reports.GET(
		"/atm-overall-success-rate",
		middleware.AuthorizeRolesOrPermissions(
			[]string{"SUPERADMIN"},
			[]string{
				"report:view-atm-overall-success-rate",
				"report:view-success-transactions",
			},
		),
		successTransactionHandler.GetATMOverall,
	)
	reports.GET(
		"/atm-acquiring-success-rate",
		middleware.AuthorizeRolesOrPermissions(
			[]string{"SUPERADMIN"},
			[]string{
				"report:view-atm-acquiring-success-rate",
				"report:view-success-transactions",
			},
		),
		successTransactionHandler.GetATMAcquiring,
	)
	reports.GET(
		"/atm-onus-success-rate",
		middleware.AuthorizeRolesOrPermissions(
			[]string{"SUPERADMIN"},
			[]string{
				"report:view-atm-onus-success-rate",
				"report:view-success-transactions",
			},
		),
		successTransactionHandler.GetATMOnus,
	)
	reports.GET(
		"/atm-offus-success-rate",
		middleware.AuthorizeRolesOrPermissions(
			[]string{"SUPERADMIN"},
			[]string{
				"report:view-atm-offus-success-rate",
				"report:view-success-transactions",
			},
		),
		successTransactionHandler.GetATMOffus,
	)
	reports.GET(
		"/atm-issuing-success-rate",
		middleware.AuthorizeRolesOrPermissions(
			[]string{"SUPERADMIN"},
			[]string{
				"report:view-atm-issuing-success-rate",
				"report:view-success-transactions",
			},
		),
		successTransactionHandler.GetATMIssuing,
	)
	reports.GET(
		"/pos-overall-success-rate",
		middleware.AuthorizeRolesOrPermissions(
			[]string{"SUPERADMIN"},
			[]string{
				"report:view-pos-overall-success-rate",
				"report:view-success-transactions",
			},
		),
		successTransactionHandler.GetPOSOverall,
	)
	reports.GET(
		"/pos-acquiring-success-rate",
		middleware.AuthorizeRolesOrPermissions(
			[]string{"SUPERADMIN"},
			[]string{
				"report:view-pos-acquiring-success-rate",
				"report:view-success-transactions",
			},
		),
		successTransactionHandler.GetPOSAcquiring,
	)
	reports.GET(
		"/pos-onus-success-rate",
		middleware.AuthorizeRolesOrPermissions(
			[]string{"SUPERADMIN"},
			[]string{
				"report:view-pos-onus-success-rate",
				"report:view-success-transactions",
			},
		),
		successTransactionHandler.GetPOSOnus,
	)
	reports.GET(
		"/pos-offus-success-rate",
		middleware.AuthorizeRolesOrPermissions(
			[]string{"SUPERADMIN"},
			[]string{
				"report:view-pos-offus-success-rate",
				"report:view-success-transactions",
			},
		),
		successTransactionHandler.GetPOSOffus,
	)
	reports.GET(
		"/pos-issuing-success-rate",
		middleware.AuthorizeRolesOrPermissions(
			[]string{"SUPERADMIN"},
			[]string{
				"report:view-pos-issuing-success-rate",
				"report:view-success-transactions",
			},
		),
		successTransactionHandler.GetPOSIssuing,
	)
	reports.GET(
		"/switch-overall-success-rate",
		middleware.AuthorizeRolesOrPermissions(
			[]string{"SUPERADMIN"},
			[]string{
				"report:view-switch-overall-success-rate",
				"report:view-success-transactions",
			},
		),
		successTransactionHandler.GetSwitchOverall,
	)
	reports.GET(
		"/switch-onus-success-rate",
		middleware.AuthorizeRolesOrPermissions(
			[]string{"SUPERADMIN"},
			[]string{
				"report:view-switch-onus-success-rate",
				"report:view-success-transactions",
			},
		),
		successTransactionHandler.GetSwitchOnus,
	)
	reports.GET(
		"/switch-offus-success-rate",
		middleware.AuthorizeRolesOrPermissions(
			[]string{"SUPERADMIN"},
			[]string{
				"report:view-switch-offus-success-rate",
				"report:view-success-transactions",
			},
		),
		successTransactionHandler.GetSwitchOffus,
	)
	reports.GET(
		"/switch-issuing-success-rate",
		middleware.AuthorizeRolesOrPermissions(
			[]string{"SUPERADMIN"},
			[]string{
				"report:view-switch-issuing-success-rate",
				"report:view-success-transactions",
			},
		),
		successTransactionHandler.GetSwitchIssuing,
	)
	reports.GET(
		"/success-rate-trend",
		middleware.AuthorizeRolesOrPermissions(
			[]string{"SUPERADMIN"},
			[]string{
				"report:view-success-transactions",
				"report:view-atm-overall-success-rate",
				"report:view-atm-acquiring-success-rate",
				"report:view-atm-onus-success-rate",
				"report:view-atm-offus-success-rate",
				"report:view-atm-issuing-success-rate",
				"report:view-pos-overall-success-rate",
				"report:view-pos-acquiring-success-rate",
				"report:view-pos-onus-success-rate",
				"report:view-pos-offus-success-rate",
				"report:view-pos-issuing-success-rate",
				"report:view-switch-overall-success-rate",
				"report:view-switch-onus-success-rate",
				"report:view-switch-offus-success-rate",
				"report:view-switch-issuing-success-rate",
			},
		),
		successTransactionHandler.GetTrend,
	)
	reports.GET(
		"/success-transactions",
		middleware.AuthorizeRolesOrPermissions(
			[]string{"SUPERADMIN"},
			[]string{
				"report:browse-success-transactions",
				"report:view-success-transactions",
			},
		),
		successTransactionHandler.ListTransactions,
	)
	reports.GET(
		"/ebirr-cardless-withdrawal",
		middleware.AuthorizeRolesOrPermissions([]string{}, []string{"report:view-ebirr-cardless-withdrawal"}),
		ebirrCardlessHandler.GetReport,
	)
	reports.GET(
		"/atm-transactions",
		middleware.AuthorizeRolesOrPermissions(
			[]string{"SUPERADMIN"},
			[]string{"terminal:view-atm-transaction"},
		),
		terminalTransactionHandler.GetByTerminal,
	)
	reports.GET(
		"/pos-transactions",
		middleware.AuthorizeRolesOrPermissions(
			[]string{"SUPERADMIN"},
			[]string{"terminal:view-pos-transaction"},
		),
		terminalTransactionHandler.GetByTerminal,
	)
	reports.GET(
		"/atm-terminal-comparison",
		middleware.AuthorizeRolesOrPermissions(
			[]string{"SUPERADMIN"},
			[]string{"terminal:view-atm-transaction"},
		),
		terminalTransactionHandler.GetAtmComparison,
	)
	reports.GET(
		"/pos-terminal-comparison",
		middleware.AuthorizeRolesOrPermissions(
			[]string{"SUPERADMIN"},
			[]string{"terminal:view-pos-transaction"},
		),
		terminalTransactionHandler.GetPosComparison,
	)
}
